version: '3.8'

services:
  app:
    build: .
    ports:
      - "8090:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=notes_app
      - DB_USER=notes_user
      - DB_PASSWORD=notes_password

  db:
    image: mariadb:10.9
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: notes_app
      MYSQL_USER: notes_user
      MYSQL_PASSWORD: notes_password
    ports:
      - "3307:3306"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql